//! Maelstrom DSP backend, via extendr.
//!
//! Exposes the hot spots of the R engine as native routines. The R wrappers
//! are generated by `rextendr::document()` into `R/extendr-wrappers.R`.

use extendr_api::prelude::*;

/// Sparse feedback comb filter: y[i] = x[i] + g * y[i - delay].
///
/// Matches R's `stats::filter(x, c(rep(0, delay - 1), g), method = "recursive")`
/// without the dense dot product R performs over the zero taps.
fn comb(x: &[f64], delay: usize, g: f64, y: &mut [f64]) {
    for i in 0..y.len() {
        let fb = if i >= delay { y[i - delay] } else { 0.0 };
        y[i] = x[i] + g * fb;
    }
}

/// Schroeder allpass: ma[i] = x[i] - g * x[i - delay]; y[i] = ma[i] + g * y[i - delay].
///
/// Matches R's two-stage `allpass_filter` (convolution then recursive) exactly,
/// including its quirk: the convolution stage yields NA (then zeroed by R) for
/// the first `delay` samples, so `ma` is 0 there rather than `x[i]`.
fn allpass(x: &[f64], delay: usize, g: f64, y: &mut [f64]) {
    for i in 0..y.len() {
        let ma = if i < delay {
            0.0
        } else {
            x[i] - g * x[i - delay]
        };
        let y_d = if i >= delay { y[i - delay] } else { 0.0 };
        y[i] = ma + g * y_d;
    }
}

/// Schroeder reverb wet signal: mean of 4 parallel combs, then 2 series allpasses.
///
/// Bit-exact with the pure-R `schroeder_wet_r()`: same delay taps (scaled by
/// `sr / 44100`, truncated like R's `as.integer`), same gains.
/// @export
/// @param x numeric vector, mono audio
/// @param sr integer sample rate
#[extendr]
fn schroeder_wet_rust(x: Vec<f64>, sr: i32) -> Vec<f64> {
    let n = x.len();
    if n == 0 || sr <= 0 {
        return vec![0.0; n];
    }
    let scale = sr as f64 / 44100.0;
    let comb_delays = [1557.0, 1617.0, 1491.0, 1422.0]
        .map(|d| (d * scale) as usize)
        .map(|d| d.max(1));

    let mut acc = vec![0.0f64; n];
    let mut tmp = vec![0.0f64; n];
    for &d in &comb_delays {
        comb(&x, d, 0.84, &mut tmp);
        for (a, t) in acc.iter_mut().zip(tmp.iter()) {
            *a += *t / 4.0;
        }
    }

    let ap1 = ((556.0 * scale) as usize).max(1);
    let ap2 = ((441.0 * scale) as usize).max(1);
    let mut out = vec![0.0f64; n];
    allpass(&acc, ap1, 0.5, &mut tmp);
    allpass(&tmp, ap2, 0.5, &mut out);
    out
}

extendr_module! {
    mod maelstrom;
    fn schroeder_wet_rust;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn impulse_decays() {
        let n = 44100;
        let mut x = vec![0.0; n];
        x[0] = 1.0;
        let out = schroeder_wet_rust(x, 44100);
        assert!(out.iter().all(|v| v.is_finite()));
        let early: f64 = out[..4410].iter().map(|v| v * v).sum();
        let late: f64 = out[39690..].iter().map(|v| v * v).sum();
        assert!(early > late);
        assert!(late > 0.0);
    }

    #[test]
    fn comb_matches_recurrence() {
        let x = vec![1.0, 0.5, 0.25, 0.0, 0.0, 0.0, 0.0, 0.0];
        let mut y = vec![0.0; x.len()];
        comb(&x, 3, 0.5, &mut y);
        let mut expected = vec![0.0; x.len()];
        for i in 0..x.len() {
            expected[i] = x[i] + if i >= 3 { 0.5 * expected[i - 3] } else { 0.0 };
        }
        for (a, b) in y.iter().zip(expected.iter()) {
            assert!((a - b).abs() < 1e-12);
        }
    }
}
