# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib maelstrom, .registration = TRUE
NULL

#' Schroeder reverb wet signal: mean of 4 parallel combs, then 2 series allpasses.
#'
#' Bit-exact with the pure-R `schroeder_wet_r()`: same delay taps (scaled by
#' `sr / 44100`, truncated like R's `as.integer`), same gains.
#' @export
#' @param x numeric vector, mono audio
#' @param sr integer sample rate
schroeder_wet_rust <- function(x, sr) .Call(wrap__schroeder_wet_rust, x, sr)

# nolint end
